#!/usr/bin/env python3
"""Update Shadowrocket supplemental AI rules from SukkaW's Surge source."""

from __future__ import annotations

import argparse
import sys
import urllib.request
from pathlib import Path


DEFAULT_SOURCE_URL = (
    "https://raw.githubusercontent.com/SukkaW/Surge/refs/heads/master/"
    "Source/non_ip/ai.conf"
)

SUPPORTED_RULE_TYPES = {
    "DOMAIN",
    "DOMAIN-SUFFIX",
    "DOMAIN-KEYWORD",
    "URL-REGEX",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-url", default=DEFAULT_SOURCE_URL)
    parser.add_argument("--output", default="shadowrocket/ai-source.list")
    return parser.parse_args()


def fetch_text(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "domain-list-community"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        charset = resp.headers.get_content_charset() or "utf-8"
        return resp.read().decode(charset)


def convert(source: str) -> tuple[list[str], dict[str, int]]:
    rules: set[tuple[str, str]] = set()
    skipped: dict[str, int] = {}

    for raw_line in source.splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue

        rule_type, sep, value = line.partition(",")
        rule_type = rule_type.strip().upper()
        if not sep:
            skipped[rule_type] = skipped.get(rule_type, 0) + 1
            continue

        value = value.split(",", 1)[0].strip()
        if not value:
            skipped[rule_type] = skipped.get(rule_type, 0) + 1
            continue

        if rule_type not in SUPPORTED_RULE_TYPES:
            skipped[rule_type] = skipped.get(rule_type, 0) + 1
            continue

        if rule_type != "URL-REGEX":
            value = value.lower()
        rules.add((rule_type, value))

    return [f"{rule_type},{value}" for rule_type, value in sorted(rules)], skipped


def main() -> int:
    args = parse_args()
    source = fetch_text(args.source_url)
    rules, skipped = convert(source)
    if not rules:
        print("no supported Shadowrocket AI rules found", file=sys.stderr)
        return 1

    skipped_summary = ", ".join(f"{key}={value}" for key, value in sorted(skipped.items()))
    lines = [
        "# Generated by scripts/update_ai_source.py",
        f"# Source: {args.source_url}",
    ]
    if skipped_summary:
        lines.append(f"# Skipped: {skipped_summary}")
    lines.extend(["", *rules, ""])

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(rules)} Shadowrocket AI rules to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
